### ISSUE TITLE
정적 페이지의 첫 화면 메뉴

### ISSUE THREAD

**Issue by J-S-Kim** [17-1-SKKU-OSS/032A#5]
정적 페이지의 첫 화면이

code페이지가 아닌데 code가 bold 표시가 되어있는 것을
수정하면 조금 더 직관적이고 좋을 것 같습니다.

**Comment by gold9598** [comment]
수정하였습니다.
index.html의 <li = active ...> 를 <li> 로 수정하여 bold 처리 삭제하였습니다.
