### ISSUE TITLE
홈페이지 글자 수정할 부분 조언 구합니다.

### ISSUE THREAD

**Issue by gold9598** [17-1-SKKU-OSS/032A#6]
Our Best Project 부분과 Create Amazing Things 부분에서 수정이 필요한데, 어떤 내용으로 수정해야 할지 의논할 필요가 있하고 생각합니다.

**Comment by J-S-Kim** [comment]
음 저는
하나는 NERDcommenter가 무엇인지 소개하는 내용으로
하나는 저희가 프로젝트에 어떤 기여를 했는지 설명하는 내용으로 하는 것이
적합하다고 생각합니다.

**Comment by Skian12** [comment]
Create Amazing Things 부분에서
NERD Commenter라고 쓰고
밑에 간단한 소개를 해주시면 될 것 같습니다.

그리고 Our Best Project 부분에서는 Our Contribution이라고 쓰시고
밑에 각각의 제목을 써 주시고,
그 제목을 누를경우 펼쳐져서 (이 기능은 불가능하면 제목 밑에다가 해당내용을 적어주시면 되겠습니다.)
각각의 사진과 함께 저희가 한 내용들을 설명하는 형태가 좋을 것같습니다.
아니라면, 먼저 제목들만 써주고 밑에 새로운 칸을 만들어서
각각에 대한 사진 및 설명을 넣는 방식으로 하는게 좋을것 같습니다,

**Comment by Skian12** [comment]
혹시 내용부분은 한글로 써주실 수 있나요

**Comment by gold9598** [comment]
네 반영하겠습니다.
구체적인 내용도 있으면 더욱 감사하겠습니다.

**Comment by Skian12** [comment]
예. pull request 완료되는대로 합류하겠습니다.
혹시 막히는 부분 있으시면 먼저 대략적으로만 써주셔도 될 것 같습니다.

**Comment by gold9598** [comment]
Our best project 부분은 이렇게 수정하겠습니다.
Our best project -> Our contribution으로
start your project는 see what we have done을 한 다음에 클릭하면 열리는 방식으로 되도록 만들어 보겠습니다.
Changed>
ToggleSlide JQuary 함수가 동작하지 않아서 page linking으로 동작하게 바꾸었습니다.
